#!/bin/bash 

Installingpackages () {
yum install epel-release -y

yum install wget -y
yum install git -y
yum install http -y 
yum install zip -y
yum install unzip -y 
yum install vim -y
yum install tree -y


}

